# Workflow derived from https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml
# Need help debugging build failures? Start at https://docs.github.com/en/actions
on:
  push:
    branches: [main, master]
  pull_request:

name: python-package-check.yaml

permissions: read-all

jobs:
  python-package-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (Python ${{ matrix.config.python-version }})

    defaults:
      run:
        working-directory: ./python # mirrors R's working-directory

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   python-version: '3.12'}
          - {os: windows-latest, python-version: '3.12'}
          # - {os: ubuntu-latest,  python-version: '3.8'}
          - {os: ubuntu-latest,  python-version: '3.10'}
          - {os: ubuntu-latest,  python-version: '3.12'}

    env:
      PIP_NO_INPUT: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.python-version }}

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - run: pytest

      - run: python -m build
